version: '3'

services:
  web:
    hostname: slam-php-apache
    container_name: slam-php-apache
    image: "image.php-apache:1.4"
    ports:
      - "0.0.0.0:80:80"
      #- "0.0.0.0:53682:53682"
    volumes:
      - "/media/proyectos/Comfueg/:/app/"
      - "/media/proyectos/Comfueg/docker/rclone/:/root/.config/rclone/ "
      - "/media/proyectos/Comfueg/storage/app/Comfueg-SLAM/:/datarclone/"
    restart: unless-stopped
    network_mode: bridge
    links:
      - database
  database:
    hostname: slam-mysql
    container_name: mysql
    image: "image.mysql:1.0"
    ports:
      - "3306:3306"
    volumes:
      - "/media/proyectos/mysql/Data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD==@ndres0426
    restart: unless-stopped
    network_mode: bridge
  dns:
    hostname: slam-coredns
    container_name: coredns
    image: "image.coredns:1.0"
    ports:
      - "53:53/udp"
    volumes:
      - "/media/proyectos/Coredns:/CoreDNS"
    restart: unless-stopped
    network_mode: bridge
    command: -conf /CoreDNS/Corefile
volumes:
  db-aircontrol: